config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update] do
    resources :teams, only: [:new ,:index ,:create]do
      collection do
        get 'war'
        get 'win'
        get 'lose'
        get 'ememy'
      end
    end
  end
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
  resources :wars, only:[:index]

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user
  validates :content, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    @group = Group.find(params[:group_id])
    @messages = @group.messages.includes(:user).where('id > ?', params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group
  before_action :set_members

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  def set_members
    @members = GroupUser.where(group_id: "#{@group.id}")
  end
end

app/views/messages/_main_chat.html.haml
.main-chat
  .main-chat__group-info
    .main-chat__group-info__left-box
      .main-chat__group-info__left-box__current-group
        = @group.name
      .main-chat__group-info__left-box__members-list
        Member : 
        .main-chat__group-info__left-box__members-list__member
        - @members.each do |member|
          = User.find(member.user_id).name
    .main-chat__group-info__right-box
      .main-chat__group-info__right-box__btn
        = link_to users_path do
          .main-chat__group-info__right-box__btn_war
            WAR
      .main-chat__group-info__right-box__btn
        = link_to edit_group_path(@group) do
          .main-chat__group-info__right-box__btn_edit
            Edit
  .main-chat__message-list
    = render @messages

  .main-chat__message-form
    .main-chat__message-form__new-message
      .main-chat__message-form__new-message__input-area
        = form_for [@group, @message] do |f|
          = f.text_field :content, id: 'new_message', class: 'main-chat__message-form__new-message__input-area__text', placeholder: 'type a message'
          = f.label :image, class: 'main-chat__message-form__new-message__input-area__image' do
            = icon('fas', 'image', class: 'icon')
            = f.file_field :image, class: 'hidden'
          = f.submit 'Send', class: 'main-chat__message-form__new-message__input-area__send-btn'

app/views/messages/_main_chat_war.html.haml
.main-chat
  .main-chat__group-info
    .main-chat__group-info__left-box
      .main-chat__group-info__left-box__current-group
        ChatSpace
      .main-chat__group-info__left-box__members-list
        Member :
        .main-chat__group-info__left-box__members-list__member
          = current_user.name
    .main-chat__group-info__right-box
      .main-chat__group-info__right-box__btn
        = link_to users_path do
          .main-chat__group-info__right-box__btn_war
            WAR

app/views/messages/_message.html.haml
.main-chat__message-list__message{data: {message: {id: message.id}}}
  .main-chat__message-list__message__upper
    .main-chat__message-list__message__upper__user
      = message.user.name
    .main-chat__message-list__message__upper__date
      = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
  .main-chat__message-list__message__main
    - if message.content.present?
      .main-chat__message-list__message__main__contents
        = message.content
    = image_tag message.image.url, class: 'main-chat__message-list__message__main__image' if message.image.present?

app/views/messages/_side_bar.html.haml
.side-bar
  .side-bar__user-name
    .side-bar__user-name__name-box
      .side-bar__user-name__name-box__user
        = current_user.name
      .side-bar__user-name__name-box__icon
        = link_to new_group_path do
          = icon('far', 'edit')
        = link_to edit_user_path(current_user) do
          = icon('fas', 'cog')
  .side-bar__group-list
    - current_user.groups.each do |group|
      = link_to group_messages_path(group) do
        .side-bar__group-list__group-name
          = group.name
        .side-bar__group-list__latest-message
          = group.show_last_message

app/views/messages/index.html.haml
.wrapper
  = render "side_bar"
  = render "main_chat"