config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update] do
    resources :teams, only: [:new ,:index ,:create]do
      collection do
        get 'war'
        get 'win'
        get 'lose'
        get 'ememy'
      end
    end
  end
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
  resources :wars, only:[:index]

end

app/views/layouts/_chat_contents.html.haml
- current_user.teams.each do |team|
  - if(user_teams_path(team.id) == request.path)
    - team.char.chars.each do|t|
      - @chars.each do|char|
        - if(char.name == t)
          .char_block
            .war-main-chat__message-list__char-name
              - if char.element_id == 1
                .fire.charname
                  = char.name
              - if char.element_id == 2
                .water.charname
                  = char.name
              - if char.element_id == 3
                .wood.charname
                  = char.name
              - if char.element_id == 4
                .lightness.charname
                  = char.name
              - if char.element_id == 5
                .darkness.charname
                  = char.name
              .status
                - @movements.each do|movement|
                  - if(movement.id == char.movement_id)
                    = movement.name
                    %br
                %div
                  %span 生命
                  .params
                    - for num in 1..(char.vitality/50).to_i do
                      %span ■
                    %br
                %div
                  %span 攻力
                  .params
                    - for num in 1..(char.attack/5).to_i do
                      %span ■
                    %br
                %div
                  %span 速度
                  .params
                    - for num in 1..(char.speed*2).to_i do
                      %span ■
                    %br
                %br

app/views/layouts/_chat_footer.html.haml
.war-main-chat__message-form

app/views/layouts/_chat_header.html.haml
.war-main-chat__group-info
  .war-main-chat__group-info__left-box
    .war-main-chat__group-info__left-box__current-group
      CHARACTER'S WAR
  .war-main-chat__group-info__right-box
    .war-main-chat__group-info__right-box__btn
      = link_to war_user_teams_path(current_user) do
        .war-main-chat__group-info__right-box__btn_chat
          WAR
    .war-main-chat__group-info__right-box__btn
      = link_to users_path do
        .war-main-chat__group-info__right-box__btn_chat
          RANK
    .war-main-chat__group-info__right-box__btn
      = link_to root_path do
        .war-main-chat__group-info__right-box__btn_chat
          Chat

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/_side_bar.html.haml
.war-side-bar
  .war-side-bar__user-name
    .war-side-bar__user-name__name-box
      .war-side-bar__user-name__name-box__user
        = current_user.name
      .war-side-bar__user-name__name-box__icon
        = link_to new_user_team_path(current_user) do
          = icon('far', 'edit')
        = link_to edit_user_path(current_user) do
          = icon('fas', 'cog')
  .war-side-bar__group-list
    - current_user.teams.each do |team|
      = link_to user_teams_path(team) do
        .war-side-bar__group-list__latest-message
          = "#{team.char}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %script{src: "https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"}
    %script{src: "https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"}
    %meta{content:  "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/notifications'
    = yield